import router from "express";
const myRouter = router.Router();
import{createCar, getAllCars, getCarByPlateNumber, deleteCar,updateCar} from "../controllers/carController.js";
import { verifyToken } from "../middleware/authmiddleware.js";
myRouter.post('/create', verifyToken, createCar);
myRouter.get('/', verifyToken, getAllCars);
myRouter.get('/:platenumber', verifyToken, getCarByPlateNumber);
myRouter.delete('/:platenumber', verifyToken, deleteCar);
myRouter.put('/:platenumber', verifyToken, updateCar);
export default myRouter;