import router from "express";
const myRouter = router.Router();
import{getAllServices, createService, deleteService, updateService, getServiceByCode} from "../controllers/serviceController.js";
import { verifyToken } from "../middleware/authmiddleware.js";
myRouter.get('/',verifyToken, getAllServices);
myRouter.post('/create', verifyToken, createService);
myRouter.delete('/:serviceCode', verifyToken, deleteService);
myRouter.put('/:serviceCode', verifyToken, updateService);
myRouter.get('/:serviceCode', verifyToken, getServiceByCode);
export default myRouter;